Loading the Dataset

In [1]:
import pandas as pd
import numpy as np
from pandas import read_csv
import numpy as np
import math
import matplotlib.pyplot as plt


In [2]:
ddf=pd.read_csv("train_0OECtn8.csv")
ddf1=pd.read_csv("test-1.csv")
ddf2=pd.read_csv('sample_submission_JPlpRcN.csv')

In [3]:
ddf.head()

row_id  user_id  category_id  video_id  age  gender            profession  \
0       1    19990           37       128   24    Male               Student   
1       2     5304           32       132   14  Female               Student   
2       3     1840           12        24   19    Male               Student   
3       4    12597           23       112   19    Male               Student   
4       5    13626           23       112   27    Male  Working Professional   

   followers  views  engagement_score  
0        180   1000              4.33  
1        330    714              1.79  
2        180    138              4.35  
3        220    613              3.77  
4        220    613              3.13

In [4]:
ddf1.head()

row_id  user_id  category_id  video_id  age  gender            profession  \
0   89198     7986           12        42   14    Male               Student   
1   89199    11278           34       115   14    Male               Student   
2   89200    17245            8       110   44  Female  Working Professional   
3   89201     9851           16       137   18    Male               Student   
4   89202    16008           34        96   47  Female                 Other   

   followers  views  
0        180    138  
1        230    840  
2        280    628  
3        270    462  
4        230    840

In [45]:
ddf2.head()

row_id  engagement_score
0   89198               5.0
1   89199               5.0
2   89200               5.0
3   89201               5.0
4   89202               5.0

Checking Missing Values

In [46]:
ddf.isnull().sum()

row_id              0
user_id             0
category_id         0
age                 0
gender              0
profession          0
followers           0
views               0
engagement_score    0
dtype: int64

In [7]:
ddf1.isnull().sum()

row_id         0
user_id        0
category_id    0
video_id       0
age            0
gender         0
profession     0
followers      0
views          0
dtype: int64

Converting Categorical Variables to Number

In [8]:
ddf.dtypes

row_id                int64
user_id               int64
category_id           int64
video_id              int64
age                   int64
gender               object
profession           object
followers             int64
views                 int64
engagement_score    float64
dtype: object

In [9]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
ddf['gender'] = labelencoder.fit_transform(ddf['gender'])
ddf['profession'] = labelencoder.fit_transform(ddf['profession'])

In [47]:
ddf.head()

row_id  user_id  category_id  age  gender  profession  followers  views  \
0       1    19990           37   24       1           1        180   1000   
1       2     5304           32   14       0           1        330    714   
2       3     1840           12   19       1           1        180    138   
3       4    12597           23   19       1           1        220    613   
4       5    13626           23   27       1           2        220    613   

   engagement_score  
0              4.33  
1              1.79  
2              4.35  
3              3.77  
4              3.13

In [11]:
ddf1['gender'] = labelencoder.fit_transform(ddf1['gender'])
ddf1['profession'] = labelencoder.fit_transform(ddf1['profession'])

In [12]:
ddf1.head()

row_id  user_id  category_id  video_id  age  gender  profession  followers  \
0   89198     7986           12        42   14       1           1        180   
1   89199    11278           34       115   14       1           1        230   
2   89200    17245            8       110   44       0           2        280   
3   89201     9851           16       137   18       1           1        270   
4   89202    16008           34        96   47       0           0        230   

   views  
0    138  
1    840  
2    628  
3    462  
4    840

In [13]:
ddf=ddf.drop(['video_id'],axis=1)

In [14]:
ddf1=ddf1.drop(['video_id'],axis=1)

Algorithms that doesn't need scaling

In [50]:
x = ddf.iloc[:, 1:-1].values
y = ddf.iloc[:, -1].values
print(X)

[[19990    37    24 ...     1   180  1000]
 [ 5304    32    14 ...     1   330   714]
 [ 1840    12    19 ...     1   180   138]
 ...
 [13655    16    25 ...     1   270   462]
 [24840     9    35 ...     2   230   819]
 [27183    25    13 ...     1   240   317]]


In [16]:
# Splitting the data into training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.2, random_state = 0)

1. Decision Tree

In [17]:
#Training the Decision Tree Regression model on the Training set
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [18]:
#Predicting the Test set results
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[4.23 3.91]
 [3.76 3.61]
 [3.11 3.56]
 ...
 [4.79 3.73]
 [3.77 3.7 ]
 [3.33 3.71]]


In [19]:
#Evaluating the model performance
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.24586342708016518

2. Random Forest

In [20]:
#Training the Random Forest Regression model on the whole dataset
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 1000, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=1000, random_state=0)

In [21]:
#Predicting the Test set results
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[4.18 3.91]
 [3.59 3.61]
 [3.75 3.56]
 ...
 [4.5  3.73]
 [3.89 3.7 ]
 [3.54 3.71]]


In [22]:
#Evaluating the Model Performance
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.45311773490445784

3.GBM

In [23]:
from sklearn.ensemble import GradientBoostingRegressor
regressor = GradientBoostingRegressor(n_estimators= 1000,max_depth=10,min_samples_split= 4,learning_rate= 0.05,random_state=0)
regressor.fit(X_train, y_train)

GradientBoostingRegressor(learning_rate=0.05, max_depth=10, min_samples_split=4,
                          n_estimators=1000, random_state=0)

In [24]:
#Predicting the Test set results
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[4.14 3.91]
 [3.48 3.61]
 [3.23 3.56]
 ...
 [4.2  3.73]
 [3.89 3.7 ]
 [3.74 3.71]]


In [25]:
#Evaluating the Model Performance
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.45902174570767684

Scaling data for other algorithms

In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

3.Linear Regression

In [27]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [28]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3.51 3.91]
 [3.05 3.61]
 [3.3  3.56]
 ...
 [3.93 3.73]
 [3.68 3.7 ]
 [3.77 3.71]]


In [29]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.24150449719173794

4.Polynomial regression

In [30]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 6)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression()

In [31]:
y_pred = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3.93 3.91]
 [2.75 3.61]
 [2.85 3.56]
 ...
 [4.16 3.73]
 [3.99 3.7 ]
 [3.58 3.71]]


In [32]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.35368257245623336

Utilizing Training data to only train and test data for testing purpose

In [33]:
ddf1.head()

row_id  user_id  category_id  age  gender  profession  followers  views
0   89198     7986           12   14       1           1        180    138
1   89199    11278           34   14       1           1        230    840
2   89200    17245            8   44       0           2        280    628
3   89201     9851           16   18       1           1        270    462
4   89202    16008           34   47       0           0        230    840

In [34]:
#Implementing Random Forest
# storing required test data value in variable w

w=ddf1.iloc[:,1:].values

In [35]:
ddf1.head()

row_id  user_id  category_id  age  gender  profession  followers  views
0   89198     7986           12   14       1           1        180    138
1   89199    11278           34   14       1           1        230    840
2   89200    17245            8   44       0           2        280    628
3   89201     9851           16   18       1           1        270    462
4   89202    16008           34   47       0           0        230    840

In [36]:
# for training data
X = ddf.iloc[:, 1:-1].values      
y = ddf.iloc[:, -1].values 

In [37]:
#from sklearn.ensemble import GradientBoostingRegressor
#regressor = GradientBoostingRegressor(n_estimators= 1000,max_depth=10,min_samples_split= 4,learning_rate= 0.05,random_state=0)
#regressor.fit(X, y)

In [38]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 1000, random_state = 0)
regressor.fit(X, y)

RandomForestRegressor(n_estimators=1000, random_state=0)

In [39]:
w_pred = regressor.predict(w)

Adding column in test data showing predicted value

In [40]:
ddf1['engagement_score']=w_pred

In [41]:
ddf1.head()

row_id  user_id  category_id  age  gender  profession  followers  views  \
0   89198     7986           12   14       1           1        180    138   
1   89199    11278           34   14       1           1        230    840   
2   89200    17245            8   44       0           2        280    628   
3   89201     9851           16   18       1           1        270    462   
4   89202    16008           34   47       0           0        230    840   

   engagement_score  
0          4.155828  
1          3.931155  
2          2.412659  
3          2.947675  
4          1.917361

Creating dataframe containing only row_id and engagement_score from ddf1

In [42]:
finaldata=ddf1.filter(['row_id','engagement_score'],axis=1)

In [43]:
finaldata.head()

row_id  engagement_score
0   89198          4.155828
1   89199          3.931155
2   89200          2.412659
3   89201          2.947675
4   89202          1.917361

Updating result dataset into drive

In [44]:
finaldata.to_csv('result3.csv', encoding='utf-8', index=False)
#!cp rfhackathon_results.csv "/content/drive/MyDrive/avhackathon"